### ISSUE TITLE
RAM Sharing to an OU no longer functioning.

### ISSUE THREAD

**Issue by apmclean** [aws-samples/aws-vpc-builder-cdk#15]
**Describe the bug**
Share within an OU

**To Reproduce**
Any VPC with an ou shared with

```
  dev:
    style: workloadIsolated
    vpcCidr: 10.0.0.0/16
    subnets:
      workload:
        cidrMask: 18
        sharedWith:
          - ou-abcd-efg
```

**Expected behavior**
RAM Share works

**Additional context**
CloudFormation returns 'OperationNotPermittedException;'
